---
title: "Chi-squared Test"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(stringr)
library(dplyr)
```



```{r, echo=FALSE}
root_dir <- getwd()
project_directory <- dirname(root_dir)
data_dir <- file.path(project_directory, 'raw-data')
curated_data_dir <- file.path(project_directory, 'curated-data')
plot_dir <- file.path(project_directory, 'Plots')


data_file_name <- "MailerLiteAllData.csv"
DF <- read.csv(file.path(curated_data_dir, data_file_name), stringsAsFactors = FALSE)


DF <- DF %>% dplyr::mutate(new_id = str_extract(Email, "[^@]+$"))

DF <- DF %>% dplyr::select(Email, new_id)


domains <- levels(factor(DF$new_id))
for (i in 1:length(domains)){
  # print(domains[[i]])
}
```

## Chi-square test on Percentage of Faculty Rank
```{r, warning=FALSE}
rank_sample <- c(23, 28, 49)
rank_population <- c(27.6, 30.3, 42.1)

Rank <- data.frame(rank_sample, rank_population)
Rank_test <- chisq.test(Rank)
Rank_test

```
## Chi-square test on Percentage of Gender
```{r, warning=FALSE}
gender_sample <-c(32, 68)
gender_population <-c(35.3, 64.7)
Gender <- data.frame(gender_sample, gender_population)
Gender_test <- chisq.test(Gender)
Gender_test
```
## Chi-square test Percentage of Gender on different Faculty Rank
```{r, warning=FALSE}
sample_FR_G = c(9, 14, 11, 17, 12, 37)
population_FR_G = c(11.9, 15.7, 11.9, 18.4, 11.5, 30.6)

Data_s_p <- data.frame(sample_FR_G, population_FR_G)
faculty_gender <- chisq.test(Data_s_p)
faculty_gender

```


## Chi-square test on Percentage of Gender all vs comment
```{r, warning=FALSE}
gender_sample <-c(42, 58)
gender_population <-c(32.5, 67.5)
Gender <- data.frame(gender_sample, gender_population)
Gender_test <- chisq.test(Gender)
Gender_test
```

