---
title: "Goofle_scholarID"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
```

## R Markdown


```{r}
root_dir <- getwd()
project_directory <- dirname(root_dir)
data_dir <- file.path(project_directory, 'curated-data')
plot_dir <- file.path(project_directory, 'Plots')
data_file_name <- 'StandardPart_Updated_backup.csv'
curated_data_dir <- file.path(project_directory, 'curated-data')
Data <-
  read.csv(file.path(data_dir, data_file_name), stringsAsFactors = FALSE)
```


```{r}
# link  = "https://scholar.google.com/citations?user=J1awhoMAAAAJ&hl=en"
# # link = as.character(link)
# id = strsplit(link, split = "=")
# id[[1]][2]
# 
# 
# str_extract(string = link, pattern = "=")
# 
# sub(".*user=([A-Za-z_]+)&.*", "\\1", link)
# strsplit(as.character(link),"(user=)|&")[[1]][2]
```

```{r, echo=FALSE}
Data <- Data %>%  dplyr::rowwise() %>% mutate(Google_scholarID = strsplit(Google_Scholar_link,"(user=)|&")[[1]][2])

file_name='Google_scholar_ID.csv'
write.csv(Data,file.path(curated_data_dir, file_name), row.names = FALSE)
```


