---
title: "RedCapData"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)  # install.packages("readxl") or install.packages("tidyverse")
library(plyr)
library(tibble)
library(dplyr)
```


```{r}
# C:\Users\soton\Documents\R\RedCapData\Data
# C:\Users\soton\Documents\R\OnlineSurvey\raw-data
xl_data <- "C:/Users/soton/Documents/R/OnlineSurvey/raw-data/Variables for scholarplot_v06_10192017.xlsx"
excel_sheets(path = xl_data)
```


```{r}
GSU<- read_excel(path = xl_data, sheet = "25-Data-GSU")
unique(GSU$Department)
GSU <-subset(GSU,Department !="Sociology" & Department != "History and Political Science")
unique(GSU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
GSU<- GSU[,c(5,6,10)]
colnames(GSU)<-c("FirstName", "LastName", "Email")

GSU <- GSU[complete.cases(GSU), ]

write.csv(GSU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Georgia State University.csv", row.names = FALSE)
```


```{r}
USF<- read_excel(path = xl_data, sheet = "22-Data-USF")
unique(USF$Department)
USF <-subset(USF,Department !="Sociology" & Department != "Economics")
unique(USF$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
USF<- USF[,c(5,6,10)]
colnames(USF)<-c("FirstName", "LastName", "Email")

USF <- USF[complete.cases(USF), ]

write.csv(USF,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/University of South Florida.csv", row.names = FALSE)
```


```{r}
VCU<- read_excel(path = xl_data, sheet = "20-Data-VCU")
unique(VCU$Department)
VCU <-subset(VCU,Department !="Sociology" & Department !="Political Science"  & Department != "Economics")
unique(VCU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
VCU<- VCU[,c(5,6,10)]
colnames(VCU)<-c("FirstName", "LastName", "Email")

VCU <- VCU[complete.cases(VCU), ]

write.csv(VCU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Virginia Commonwealth University.csv", row.names = FALSE)
```

```{r}
NCSU<- read_excel(path = xl_data, sheet = "14-Data-NCSU")
unique(NCSU$Department)
NCSU <-subset(NCSU,Department !="Sociology and Anthropology" & Department !="Political Science")
unique(NCSU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
NCSU<- NCSU[,c(5,6,10)]
colnames(NCSU)<-c("FirstName", "LastName", "Email")

NCSU <- NCSU[complete.cases(NCSU), ]

write.csv(NCSU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/North Carolina State University.csv", row.names = FALSE)
```


```{r}
UCF<- read_excel(path = xl_data, sheet = "4-Data-UCF")
unique(UCF$Department)
UCF <-subset(UCF,Department !="Sociology" & Department !="Political Science")
unique(UCF$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UCF<- UCF[,c(5,6,10)]
colnames(UCF)<-c("FirstName", "LastName", "Email")

UCF <- UCF[complete.cases(UCF), ]

write.csv(UCF,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/University of Central Florida.csv", row.names = FALSE)
```

```{r}
FSU<- read_excel(path = xl_data, sheet = "7-Data-FSU")
unique(FSU$Department)
FSU <-subset(FSU,Department !="Sociology" & Department !="Political Science" &  Department !="Sociology")
unique(FSU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
FSU<- FSU[,c(5,6,10)]
colnames(FSU)<-c("FirstName", "LastName", "Email")

FSU <- FSU[complete.cases(FSU), ]

write.csv(FSU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Florida State University.csv", row.names = FALSE)
```


```{r}
UC<- read_excel(path = xl_data, sheet = "1-Data-UC")
unique(UC$Department)
UC <-subset(UC,Department !="Sociology" & Department !="Political Science")
unique(UC$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UC<- UC[,c(5,6,10)]
colnames(UC)<-c("FirstName", "LastName", "Email")

UC <- UC[complete.cases(UC), ]

write.csv(UC,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/University of Cincinnati.csv", row.names = FALSE)
```

```{r}
UMD<- read_excel(path = xl_data, sheet = "3-Data-UMD")
unique(UMD$Department)
UMD <-subset(UMD, Department !="Economics" & Department !="Sociology" & Department !="Political Science" & Department !="Government and Politics")
unique(UMD$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UMD<- UMD[,c(5,6,10)]
colnames(UMD)<-c("FirstName", "LastName", "Email")

UMD <- UMD[complete.cases(UMD), ]

write.csv(UMD,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/University of Maryland.csv", row.names = FALSE)
```


```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

df_quakes_name <- read_excel(path = xl_data, sheet = "18-Data-UTSA")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

# names(NSM)

NSM <- NSM %>% select ("First Name", "Last Name", FacEmail)
colnames(NSM)<-c("FirstName", "LastName", "Email")

NSM <- NSM[complete.cases(NSM), ]

write.csv(NSM,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/NSM.csv", row.names = FALSE)
```



```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

TU<- read_excel(path = xl_data, sheet = "13-Data-TU")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(TU$Department)
TU <-subset(TU, Department !="Environmental Studies" & Department !="Sociology" & Department !="Political Science")
unique(TU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
TU<- TU[,c(5,6,10)]
colnames(TU)<-c("FirstName", "LastName", "Email")

TU <- TU[complete.cases(TU), ]

write.csv(TU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/TU.csv", row.names = FALSE)
```

```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

UIC<- read_excel(path = xl_data, sheet = "9-Data-UIC")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UIC$Department)
UIC <-subset(UIC, Department !="Economics" & Department !="Sociology" & Department !="Political Science")
unique(UIC$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UIC<- UIC[,c(5,6,10)]
colnames(UIC)<-c("FirstName", "LastName", "Email")

UIC <- UIC[complete.cases(UIC), ]

write.csv(UIC,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UIC.csv", row.names = FALSE)
```

```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

OSU<- read_excel(path = xl_data, sheet = "23-Data-OSU")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(OSU$Department)
OSU <-subset(OSU, Department !="Economics" & Department !="Sociology" & Department !="Political Science")
unique(OSU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
OSU<- OSU[,c(5,6,10)]
colnames(OSU)<-c("FirstName", "LastName", "Email")

OSU <- OSU[complete.cases(OSU), ]

write.csv(OSU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/OSU.csv", row.names = FALSE)
```


```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

UWM<- read_excel(path = xl_data, sheet = "24-Data-UWM")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UWM$Department)
UWM <-subset(UWM, Department !="Economics" & Department !="Sociology")
unique(UWM$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UWM<- UWM[,c(5,6,10)]
colnames(UWM)<-c("FirstName", "LastName", "Email")

UWM <- UWM[complete.cases(UWM), ]

write.csv(UWM,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UWM.csv", row.names = FALSE)
```

```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

TSU<- read_excel(path = xl_data, sheet = "19-Data-TSU")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(TSU$Department)
TSU <-subset(TSU, Department !="Health and Human Performance" & Department !="Political Science")
unique(TSU$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
TSU<- TSU[,c(5,6,10)]
colnames(TSU)<-c("FirstName", "LastName", "Email")

TSU <- TSU[complete.cases(TSU), ]

write.csv(TSU,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/TSU.csv", row.names = FALSE)
```


```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

UCLA <- read_excel(path = xl_data, sheet = "6-Data-UCLA")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UCLA$Department)
UCLA <-subset(UCLA, Department !="Sociology" & Department !="Political Science" 
                                  & Department !="Economics" )
unique(UCLA$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
UCLA<- UCLA[,c(5,6,10)]
colnames(UCLA)<-c("FirstName", "LastName", "Email")

UCLA <- UCLA[complete.cases(UCLA), ]

write.csv(UCLA,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UCLA.csv", row.names = FALSE)
```


```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

New_Mexico <- read_excel(path = xl_data, sheet = "21-Data-UNM")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(New_Mexico$Department)
New_Mexico <-subset(New_Mexico, Department !="Sociology" & Department !="Political Science" 
                                  & Department !="Economics" )
unique(New_Mexico$Department)

# Arizona_state_University <- Arizona_state_University %>% select ("First Name", "Last Name", FacEmail)
New_Mexico<- New_Mexico[,c(5,6,10)]
colnames(New_Mexico)<-c("FirstName", "LastName", "Email")

New_Mexico <- New_Mexico[complete.cases(New_Mexico), ]

write.csv(New_Mexico,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/New_Mexico.csv", row.names = FALSE)
```

```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

Texas_tech_University <- read_excel(path = xl_data, sheet = "16-Data-TTU")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(Texas_tech_University$Department)
Texas_tech_University <-subset(Texas_tech_University, Department !="Economics" & Department !="Political Science")
unique(Texas_tech_University$Department)

Texas_tech_University <- Texas_tech_University %>% select ("First Name", "Last Name", FacEmail)
colnames(Texas_tech_University)<-c("FirstName", "LastName", "Email")

Texas_tech_University <- Texas_tech_University[complete.cases(Texas_tech_University), ]

write.csv(Texas_tech_University,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Texas_tech_University.csv", row.names = FALSE)
```

```{r}
 El_Paso_Texas <- read_excel(path = xl_data, sheet = "17-Data-UTEP")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(El_Paso_Texas$Department)
El_Paso_Texas <-subset(El_Paso_Texas, Department !="Political Science")


# El_Paso_Texas <- El_Paso_Texas %>% select ("First Name", "Last Name", "FacEmail")
El_Paso_Texas<- El_Paso_Texas[,c(5,6,10)]
colnames(El_Paso_Texas)<-c("FirstName", "LastName", "Email")

El_Paso_Texas <- El_Paso_Texas[complete.cases(El_Paso_Texas), ]

write.csv(El_Paso_Texas,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/El_Paso_Texas.csv", row.names = FALSE)
```

```{r}
UT_Arlington <- read_excel(path = xl_data, sheet = "15-Data-UTArl")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UT_Arlington$Department)
UT_Arlington <-subset(UT_Arlington, Department !="Sociology and Anthropology" & Department !="Sociology and Anthropology")

UT_Arlington <- UT_Arlington %>% select ("First Name", "Last Name", FacEmail)
colnames(UT_Arlington)<-c("FirstName", "LastName", "Email")

UT_Arlington <- UT_Arlington[complete.cases(UT_Arlington), ]

write.csv(UT_Arlington,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UT_Arlington.csv", row.names = FALSE)
```

```{r}
UT_Austin <- read_excel(path = xl_data, sheet = "5-Data-UTA")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UT_Austin$Department)
UT_Austin <-subset(UT_Austin, Department !="Sociology" & Department !="Economics")

UT_Austin <- UT_Austin %>% select ("First Name", "Last Name", FacEmail)
colnames(UT_Austin)<-c("FirstName", "LastName", "Email")

UT_Austin <- UT_Austin[complete.cases(UT_Austin), ]

write.csv(UT_Austin,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UT_Austin.csv", row.names = FALSE)
```

```{r}
North_Texas <- read_excel(path = xl_data, sheet = "10-Data-UNT")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(North_Texas$Department)
North_Texas <-subset(North_Texas, Department!="Sociology"
                    & Department!="Political Science"
                  & Department!="Economics")

North_Texas <- North_Texas %>% select ("First Name", "Last Name", FacEmail)
colnames(North_Texas)<-c("FirstName", "LastName", "Email")

North_Texas <- North_Texas[complete.cases(North_Texas), ]

write.csv(North_Texas,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/North_Texas.csv", row.names = FALSE)
```

```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

UT_dallas <- read_excel(path = xl_data, sheet = "8-Data-UTD")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

unique(UT_dallas$Department)
UT_dallas <-subset(UT_dallas, Department!="Sociology"
                  & Department!="Political Science"
                  & Department!="Economics")
UT_dallas <- UT_dallas %>% select ("First Name", "Last Name", FacEmail)
colnames(UT_dallas)<-c("FirstName", "LastName", "Email")

UT_dallas <- UT_dallas[complete.cases(UT_dallas), ]

write.csv(UT_dallas,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UT_dallas.csv", row.names = FALSE)
```


```{r}
#DF_Sub_Day<-subset(DF, Participant_ID=="T007")

UTSA <- read_excel(path = xl_data, sheet = "18-Data-UTSA")
# NSM <-subset(df_quakes_name, College == "Natural Sciences and Mathematics")

# unique(UTSA$Department)
UTSA <-subset(UTSA, Department!="Sociology"
                  | Department!="Political Science and Geography"
                  | Department!="Environmental Science and Ecology")
UTSA <- UTSA %>% select ("First Name", "Last Name", FacEmail)
colnames(UTSA)<-c("FirstName", "LastName", "Email")

UTSA <- UTSA[complete.cases(UTSA), ]

write.csv(UTSA,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/UTSA.csv", row.names = FALSE)
```

```{r}

unique(Texas_AM$Department)
Texas_AM <- read_excel(path = xl_data, sheet = "11-Data-TA&M")


Texas_AM <-subset(Texas_AM, Department!="Economics" 
                   | Department=="Sociology"
                   | Department=="Political Science")

# names(NSM)

# Texas_AM <- Texas_AM %>% select ("First Name", "Last Name", FacEmail)
Texas_AM<- Texas_AM[,c(5,6,10)]
colnames(Texas_AM)<-c("FirstName", "LastName", "Email")

Texas_AM <- Texas_AM[complete.cases(Texas_AM), ]

write.csv(Texas_AM,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Texas_AM.csv", row.names = FALSE)
```


```{r}
unique(df_quakes_name$Department)
rest_of_uh<-subset(df_quakes_name, Department=="Decision & Information Sciences" 
                   | Department=="Psychological Health and Learning Sciences"
                   | Department=="Psychological, Health and Learning Sciences"
                   | Department=="Health and Human Performance"
                   | Department=="Optometry"
                   | Department=="Information and Logistics Technology"
                   | Department=="Pharmacological & Pharmaceutical Sciences"
                   | Department=="Pharmacy Practice & Translational Research"
                   | Department=="Engineering Technology")

# rest_of_uh <- rest_of_uh %>% select ("First Name", "Last Name", FacEmail)
rest_of_uh<- rest_of_uh[,c(5,6,10)]



colnames(rest_of_uh)<-c("FirstName", "LastName", "Email")

rest_of_uh <- rest_of_uh[complete.cases(rest_of_uh), ]

write.csv(rest_of_uh,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/rest_of_uh.csv", row.names = FALSE)

# write.csv(NSM,"C:/Users/soton/Documents/R/OnlineSurvey/curate-data/NSM.csv", row.names = FALSE)
```


```{r}
Psychology <-subset(df_quakes_name, Department == "Psychology")

# names(NSM)

Psychology <- Psychology %>% select ("First Name", "Last Name", FacEmail)
colnames(Psychology)<-c("FirstName", "LastName", "Email")

Psychology <- Psychology[complete.cases(Psychology), ]

write.csv(Psychology,"C:/Users/soton/Documents/R/RedCapData/Data/Psychology.csv", row.names = FALSE)
```



```{r}
Engineering <-subset(df_quakes_name, College == "Engineering")

# names(NSM)

Engineering <- Engineering %>% select ("First Name", "Last Name", FacEmail)
colnames(Engineering)<-c("FirstName", "LastName", "Email")

Engineering <- Engineering[complete.cases(Engineering), ]

write.csv(Engineering,"C:/Users/soton/Documents/R/RedCapData/Data/Engineering.csv", row.names = FALSE)
```

```{r}

Electrical<- subset(df_quakes_name, Department == "Electrical and Computer Engineering")


Electrical <- Electrical %>% select ("First Name", "Last Name", FacEmail)
colnames(Electrical)<-c("FirstName", "LastName", "Email")

Electrical <- Electrical[complete.cases(Electrical), ]

write.csv(Electrical,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Electrical.csv", row.names = FALSE)
```

```{r}
tab_names <- excel_sheets(path = xl_data)

list_all <- lapply(tab_names, function(x) read_excel(path = xl_data, sheet = x))

# str(list_all)

df <- rbind.fill(list_all)
str(df)

unique(df$UniversityName)

All_emails <- df %>% select ("First Name", "Last Name", FacEmail)
colnames(All_emails)<-c("FirstName", "LastName", "Email")

All_emails <- All_emails[complete.cases(All_emails), ]
write.csv(All_emails,"C:/Users/soton/Documents/R/RedCapData/Data/All_emails.csv", row.names = FALSE)
```

```{r}

Biomedical_Engineering <-subset(df_quakes_name, Department == "Biomedical Engineering")

# names(NSM)

Biomedical_Engineering <- Biomedical_Engineering %>% select ("First Name", "Last Name", FacEmail)
colnames(Biomedical_Engineering)<-c("FirstName", "LastName", "Email")

Biomedical_Engineering <- Biomedical_Engineering[complete.cases(Biomedical_Engineering), ]

write.csv(Biomedical_Engineering,"C:/Users/soton/Documents/R/OnlineSurvey/curated-data/Biomedical_Engineering.csv", row.names = FALSE)
  
```

