---
title: ""
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(glue)
library(stringr)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")

library(dplyr)
library(plotrix)
library(plotly)
library(tools)
library(plotrix)
library(plotly)
library(grid)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(reshape2)
library(plyr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
root_dir <- getwd()
project_directory<-dirname(root_dir)
data_dir <- file.path(project_directory, 'raw-data')
curated_data_dir <- file.path(project_directory, 'curated-data/SentimentData')
plot_dir <- file.path(project_directory, 'Plots')
fileName_conf_paper<-'ConfPaper.txt'
fileName_proposal<-'Proposal.txt'

```

```{r, echo=FALSE, warning=FALSE}
####-----------Source: https://www.red-gate.com/simple-talk/sql/bi/text-mining-and-sentiment-analysis-with-r/------#######
text <- readLines(file.path(curated_data_dir, fileName_proposal))
TextDoc <- Corpus(VectorSource(text))

```


```{r, echo=FALSE, warning=FALSE}
syuzhet_vector <- get_sentiment(text, method="syuzhet")
d<-get_nrc_sentiment(text)
```

```{r, echo=FALSE, warning=FALSE}
td<-data.frame(t(d))
col_num=NCOL(td)
td_new <- data.frame(rowSums(td[1:col_num]))
#Transformation and cleaning
names(td_new)[1] <- "count"
td_new <- cbind("sentiment" = rownames(td_new), td_new)
rownames(td_new) <- NULL
td_new2<-as.data.frame(td_new[1:8,])
```

```{r}
ylimit= round_any(max(td_new2$count), 10,f = ceiling)

legend_order=levels(reorder(td_new2$sentiment, -td_new2$count)) 

barplot<-ggplot(data = td_new2, aes(x = reorder(sentiment, -count), y = count)) + 
  geom_bar(aes(fill = sentiment), stat = "identity", position = "dodge")+
  theme_minimal() + 
  scale_y_continuous(breaks = seq(0, ylimit, by = 26),
                       limits = c(0, ylimit)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(
      face = "bold",
      size = 10 ,
      angle = 45,
      hjust = 1
    ),
    axis.text.y = element_text(face = "bold", size = 10),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
  )+labs(x = "", y = "Count", title = "Sentiment analysis on proposal deadlines") +
  guides(fill = guide_legend(nrow = 1))+
  # scale_fill_discrete(limits = c("anticipation", "trust", "joy", "fear",  "sadness", "surprise", "anger","disgust"))
  scale_fill_discrete(limits = legend_order[1:8])
barplot
```


```{r}
  

Data_Frame=as.data.frame(sort(colSums(prop.table(d[, 1:8]))))
Data_Frame$emotions=rownames(Data_Frame)
colnames(Data_Frame)=c("Percentage", "Emotions")
Data_Frame$Percentage=Data_Frame$Percentage*100


plot <-
  ggplot(Data_Frame, aes(x = reorder(Emotions, Percentage), y = Percentage)) +
  geom_bar(aes(fill = Emotions), stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(x = "", y = "Percentage [%]", title = "Emotions in Texts") +
  scale_y_continuous(breaks = seq(0, 35, by = 5),
                       limits = c(0, 35)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(
      face = "bold",
      size = 10 ,
      angle = 45,
      hjust = 1
    ),
    axis.text.y = element_text(face = "bold", size = 10),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 10)
  )+coord_flip()+
  guides(fill = guide_legend(nrow = 1))+
  scale_fill_discrete(limits = legend_order[1:8])
plot




plots_Proposal=ggarrange(barplot,plot, nrow = 2, ncol = 1, common.legend = TRUE,legend="bottom")
filename<-"Sntiment_proposal.pdf"
full_path<-file.path(plot_dir, filename)
ggsave(full_path, plots_Proposal, width = 8.5, height = 11, units = "in")
```




```{r, echo=FALSE, warning=FALSE}
####-----------Source: https://www.red-gate.com/simple-talk/sql/bi/text-mining-and-sentiment-analysis-with-r/------#######
text <- readLines(file.path(curated_data_dir, fileName_conf_paper))
TextDoc <- Corpus(VectorSource(text))

```


```{r, echo=FALSE, warning=FALSE}
syuzhet_vector <- get_sentiment(text, method="syuzhet")
d<-get_nrc_sentiment(text)
```

```{r, echo=FALSE, warning=FALSE}
td<-data.frame(t(d))
col_num=NCOL(td)
td_new <- data.frame(rowSums(td[1:col_num]))
#Transformation and cleaning
names(td_new)[1] <- "count"
td_new <- cbind("sentiment" = rownames(td_new), td_new)
rownames(td_new) <- NULL
td_new2<-as.data.frame(td_new[1:8,])
```

```{r}
ylimit= round_any(max(td_new2$count), 10,f = ceiling)

legend_order=levels(reorder(td_new2$sentiment, -td_new2$count)) 

barplot<-ggplot(data = td_new2, aes(x = reorder(sentiment, -count), y = count)) + 
  geom_bar(aes(fill = sentiment), stat = "identity", position = "dodge")+
  theme_minimal() + 
  scale_y_continuous(breaks = seq(0, ylimit, by = 10),
                       limits = c(0, ylimit)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(
      face = "bold",
      size = 10 ,
      angle = 45,
      hjust = 1
    ),
    axis.text.y = element_text(face = "bold", size = 10),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
  )+labs(x = "", y = "Count", title = "Sentiment analysis on conference papers") +
  guides(fill = guide_legend(nrow = 1))+
  # scale_fill_discrete(limits = c("anticipation", "trust", "joy", "fear",  "sadness", "surprise", "anger","disgust"))
  scale_fill_discrete(limits = legend_order[1:8])
barplot
```


```{r}
  

Data_Frame=as.data.frame(sort(colSums(prop.table(d[, 1:8]))))
Data_Frame$emotions=rownames(Data_Frame)
colnames(Data_Frame)=c("Percentage", "Emotions")
Data_Frame$Percentage=Data_Frame$Percentage*100


plot <-
  ggplot(Data_Frame, aes(x = reorder(Emotions, Percentage), y = Percentage)) +
  geom_bar(aes(fill = Emotions), stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(x = "", y = "Percentage [%]", title = "Emotions in Texts") +
  scale_y_continuous(breaks = seq(0, 35, by = 5),
                       limits = c(0, 35)) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(
      face = "bold",
      size = 10 ,
      angle = 45,
      hjust = 1
    ),
    axis.text.y = element_text(face = "bold", size = 10),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 10)
  )+coord_flip()+
  guides(fill = guide_legend(nrow = 1))+
  scale_fill_discrete(limits = legend_order[1:8])
plot




plots_Proposal=ggarrange(barplot,plot, nrow = 2, ncol = 1, common.legend = TRUE,legend="bottom")
filename<-"Sntiment_conf_paper.pdf"
full_path<-file.path(plot_dir, filename)
ggsave(full_path, plots_Proposal, width = 8.5, height = 11, units = "in")
```
