---
title: "Model Plots"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(GGally)
library(reshape2)
library(plyr)
library(nnet)
library(MASS)
library(caret)
library(mlbench)
library(rms)
require(tidyr)
library(superml)
library(randomForest)
library(aod)
library(pROC)
library(interplot)
library(sjPlot)
library(grid)
library(gridExtra)
library(ggpubr)
library(freqtables)
```


```{r, echo=FALSE}
  root_dir <- getwd()
  project_directory <- dirname(root_dir)
  data_dir <- file.path(project_directory, 'raw-data')
  curated_data_dir <- file.path(project_directory, 'curated-data')
  plot_dir <- file.path(project_directory, 'Plots')
```


```{r, echo=FALSE}

data_processing_model <- function(data_file_name) {
  root_dir <- getwd()
  project_directory <- dirname(root_dir)
  data_dir <- file.path(project_directory, 'raw-data')
  curated_data_dir <- file.path(project_directory, 'curated-data')
  plot_dir <- file.path(project_directory, 'Plots')
  
  print(data_file_name)
  lm_DF <-
    read.csv(file.path(curated_data_dir, data_file_name),
             stringsAsFactors = FALSE)
  # count(lm_DF$SR)
  
  lm_DF$RS <- as.factor(lm_DF$RS)
  lm_DF$WH <- as.factor(lm_DF$WH)
  lm_DF$NP <- as.factor(lm_DF$NP)
  lm_DF$BF <- as.factor(lm_DF$BF)
  lm_DF$DWH <- as.factor(lm_DF$DWH)
  lm_DF$FA <- as.factor(lm_DF$FA)
  lm_DF$TS <- as.factor(lm_DF$TS)
  lm_DF$DS <- as.factor(lm_DF$DS)
  lm_DF$PR <- as.factor(lm_DF$PR)
  lm_DF$FR <- as.factor(lm_DF$FR)
  
  
  NullModel <- glm(SR ~ 1, data = lm_DF, family = "binomial")
  FullModel <- glm(SR ~ ., data = lm_DF, family = "binomial")
  BEmodel <-
    stepAIC(FullModel, direction = "backward", trace = FALSE)
  summary(BEmodel)
  
  return(BEmodel)
}

```

## Configuration 20
```{r, echo=FALSE}
model_20 <- data_processing_model("model_data_conf20.csv")
summary(model_20)
```



## Configuration 30
```{r, echo=FALSE}
model_30 <- data_processing_model("model_data_conf30.csv")
summary(model_30)
```



## Configuration 50
```{r, echo=FALSE}
model_50 <- data_processing_model("model_data_conf50.csv")
summary(model_50)
```




```{r}
dummy_df <- data.frame(
  x = c(0, 1, 0, 1),
  y = c(1, 0, 0, 1),
  group = c('a', 'a', 'b', 'b')
)


  dummy_plot <- ggplot(dummy_df, aes(x = x, y = y, group = group)) +
    geom_line(scale = 0.9, color = "white") +
    theme_bw() 
  
  dummy_plot
```


## Dummy plot

```{r, echo=FALSE}
dummy_df <- data.frame(
  x = c(0, 1, 0, 1),
  y = c(1, 0, 0, 1),
  group = c('a', 'a', 'b', 'b')
)

y_title = expression(paste(italic("P", "S20%")))

SectionA_draw_dummy_plot <- function(plot_title, y_title) {
  if (plot_title != "") {
    title = element_text(hjust = 0.5,
                         size = 7,
                         face = "bold")
  }
  
  if (plot_title == "") {
    title = element_blank()
  }
  dummy_plot <- ggplot(dummy_df, aes(x = x, y = y, group = group)) +
    geom_line(scale = 0.9, color = "white") +
    theme_bw() +
    theme(
      plot.title = title,
      axis.title.x = element_text(),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.x = element_text(
        face = "bold",
        size = 6,
        angle = 30,
        hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 6),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    ) + labs(y = element_blank(), x = "", title = plot_title) +
    scale_y_continuous(
      limits = c(0.0, 1),
      breaks = c(0.0, 0.25, 0.50, 0.75, 1),
      labels = c(
        "0.00" = "",
        "0.25" = "",
        "0.50" = "",
        "0.75" = "",
        "1" = ""
      )
    ) +
    scale_x_continuous(
      limits = c(0.0, 1),
      breaks = c(0.0, 0.25, 0.50, 0.75, 1),
      labels = c(
        "0.00" = "",
        "0.25" = "",
        "0.50" = "",
        "0.75" = "",
        "1" = ""
      )
    )
  
  return(dummy_plot)
  dummy_plot
}




SectionB_draw_dummy_plot <-
  function(plot_title, y_title, configuration) {
    y_title = bquote( ~ italic("P"[.(configuration)]))
    dummy_plot <- ggplot(dummy_df, aes(x = x, y = y, group = group)) +
      geom_line(scale = 0.9, color = "white") +
      theme_bw() +
      theme(
        plot.title = element_blank(),
        axis.title.x = element_text(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(
          face = "bold",
          size = 7,
          angle = 30,
          hjust = 1
        ),
        axis.text.y = element_text(face = "bold", size = 6),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
      ) + labs(y = y_title, x = "", title = plot_title) +
      scale_y_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "0%",
          "0.25" = "25%",
          "0.50" = "50%",
          "0.75" = "75%",
          "1" = "100%"
        )
      ) +
      scale_x_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "",
          "0.25" = "",
          "0.50" = "",
          "0.75" = "",
          "1" = ""
        )
      )
    
    return(dummy_plot)
    dummy_plot
  }



SectionC_draw_dummy_plot <-
  function(plot_title, y_title, configuration) {
    if (plot_title != "") {
      title = element_text(hjust = 0.5,
                           size = 7,
                           face = "bold")
    }
    
    if (plot_title == "") {
      title = element_blank()
    }
    
    if (plot_title == "Trait Anxiety") {
      y_title = bquote(~ italic("P"[.(configuration)]))
    }
    if (plot_title != "Trait Anxiety") {
      y_title = element_blank()
    }
    
    
    dummy_plot <-
      ggplot(dummy_df, aes(x = x, y = y, group = group)) +
      geom_line(scale = 0.9, color = "white") +
      theme_bw() +
      theme(
        plot.title = title,
        axis.title.x = element_text(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(
          face = "bold",
          size = 7,
          angle = 30,
          hjust = 1
        ),
        axis.text.y = element_text(face = "bold", size = 6),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
      ) + labs(y = y_title, x = "", title = plot_title) +
      scale_y_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "0%",
          "0.25" = "25%",
          "0.50" = "50%",
          "0.75" = "75%",
          "1" = "100%"
        )
      ) + scale_x_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "",
          "0.25" = "",
          "0.50" = "",
          "0.75" = "",
          "1" = ""
        )
      )
    return(dummy_plot)
    dummy_plot
  }

# draw_dummy_plot_blank_title <- function(plot_title) {
#   dummy_plot <- ggplot(dummy_df, aes(x=x, y=y, group=group)) + 
#     geom_line(scale = 0.9) +
#     # theme_minimal() +
#     theme(
#       plot.title = element_blank(),
#       axis.title.x=element_text(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank(),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank()) + labs(title =  plot_title, x= "")
#     
#   return(dummy_plot)
#   dummy_plot
# }

```

## plot in new orientation

```{r, echo=FALSE}
model_plot_sectionA <-
  function(model_name,
           item,
           modified,
           Plot_title,
           configuration) {
    print(model_name)
    if (item == "NP" | item == "H" | item == "TA") {
      y_title = bquote( ~ italic("P"[.(configuration)]))
      
      # labs(title = bquote(italic(.(title_list[i])) ~ .(title_suffix)))
      
      y_text = element_text(face = "bold")
    } else{
      y_title = element_blank()
      y_text = element_blank()
    }
    
    
    if (configuration != 20) {
      plot_title_ = element_blank()
      
    }
    if (configuration == 20) {
      plot_title_ = element_text(hjust = 0.5,
                                 face = "bold",
                                 size = 7)
    }
    
    
    # plot_model(toy_model, type=("pred"),
    #                   terms=c("Sepal.Width","Species"), colors = "Set2") + aes(linetype=group, color=group)

    
    
    if (item == "NP" |
        item == "H" |
        item == "TA") {
      plt = plot_model(model_name, type = "pred", terms = item) +
        theme(
          plot.title = plot_title_,
          panel.grid = element_blank(),
          axis.text.x = element_text(face = "bold", size = 6),
          axis.text.y = element_text(face = "bold", size = 6)
        ) +
        labs(y = y_title, x = "", title = Plot_title) + scale_y_continuous(
          limits = c(0.0, 1),
          breaks = c(0.0, 0.25, 0.50, 0.75, 1),
          labels = c(
            "0.00" = "0%",
            "0.25" = "25%",
            "0.50" = "50%",
            "0.75" = "75%",
            "1" = "100%"
          )
        ) + theme(
          axis.text.y = y_text,
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank()
        ) + scale_x_discrete(limits = modified)
      return(plt)
    } else {
      plt = plot_model(model_name, type = "pred", terms = item) +
        theme(
          plot.title = plot_title_,
          panel.grid = element_blank(),
          axis.text.x = element_text(face = "bold", size = 6),
          axis.text.y = element_text(face = "bold", size = 6)
        ) +
        labs(y = element_blank(), x = "", title = Plot_title) +
        scale_y_continuous(
          limits = c(0.0, 1),
          breaks = c(0.0, 0.25, 0.50, 0.75, 1),
          labels = c(
            "0.00" = "0%",
            "0.25" = "25%",
            "0.50" = "50%",
            "0.75" = "75%",
            "1" = "100%"
          )
        ) + theme(
          axis.text.y = y_text,
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank()
        ) + scale_x_discrete(limits = modified)
      return(plt)
    }
    
  }
```



```{r, echo=FALSE}
model_plot_sectionB <-
  function(model_name,
           item,
           modified,
           Plot_title,
           configuration) {
    print(model_name)
    if (item == "H" | item == "TA") {
      y_title = bquote( ~ italic("P"[.(configuration)]))
      
      y_text = element_text(face = "bold")
    } else{
      y_title = element_blank()
      y_text = element_blank()
    }
    
    
    if (configuration != 20) {
      plot_title_ = element_blank()
      
    }
    if (configuration == 20) {
      plot_title_ = element_text(hjust = 0.5,
                                 face = "bold",
                                 size = 7)
    }
    
    if (item == "H" | item == "TA" | item == "E") {
      plt = plot_model(model_name, type = "pred", terms = item) +
        theme(
          plot.title = plot_title_,
          panel.grid = element_blank(),
          axis.text.x = element_text(face = "bold", size = 6),
          axis.text.y = element_text(face = "bold", size = 6)
        ) +
        labs(y = y_title, x = "", title = Plot_title) + scale_y_continuous(
          limits = c(0.0, 1),
          breaks = c(0.0, 0.25, 0.50, 0.75, 1),
          labels = c(
            "0.00" = "0%",
            "0.25" = "25%",
            "0.50" = "50%",
            "0.75" = "75%",
            "1" = "100%"
          )
        ) + theme(
          axis.text.y = y_text,
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank()
        )
      return(plt)
    } else {
      plt = plot_model(model_name, type = "pred", terms = item) +
        theme(
          plot.title = plot_title_,
          panel.grid = element_blank(),
          axis.text.x = element_text(face = "bold", size = 6),
          axis.text.y = element_text(face = "bold", size = 6)
        ) +
        labs(y = element_blank(), x = "", title = Plot_title) +
        scale_y_continuous(
          limits = c(0.0, 1),
          breaks = c(0.0, 0.25, 0.50, 0.75, 1),
          labels = c(
            "0.00" = "0%",
            "0.25" = "25%",
            "0.50" = "50%",
            "0.75" = "75%",
            "1" = "100%"
          )
        ) + theme(
          axis.text.y = y_text,
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank()
        ) + scale_x_discrete(limits = modified)
      return(plt)
    }
    
  }
```




```{r, echo=FALSE}
np_actual = c("1" = "NP1", "2" = "NP2", "3"="NP3")
fa_actual = c("1" = "NSF", "2" = "NIH", "3" = "DOE", "4" = "DOD", "5" = "NASA", "6" = "OT")
TS_actual = c("1" = "TS1", "2" = "TS2")
DS_actual = c("1" = "DS1", "2" = "DS2")
BF_actual = c("1" = "BF1", "2" = "BF2")
PR_actual = c("1" = "PR1", "2" = "PR2", "3" = "PR3", "4" = "PR4", "5" = "PR5")
RS_actual = c("1" = "RS1", "2" = "RS2")
FR_actual = c("1" = "FR1", "2" = "FR2", "3" = "FR3")
H_actual = c("0" = "0", "50" = "50", "100" = "100", "150" ="150", "200" = "200")
```

## SectionA plots
```{r, echo=FALSE}
plot_list <- list()
plot_item <- c("NP", "FA", "TS")
title <- c("Number of Proposals", "Funding Agency", "Time of Submission")

modified_ticx = list(np_actual, fa_actual, TS_actual, H_actual)

configuration = 20
for (item in 1:length(plot_item)){
  plot = model_plot_sectionA(model_20, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("Break Frequency", "")
dummy_PR <- SectionA_draw_dummy_plot("Pilot Research", "")


plot_A_20 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  plot_list[[3]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 5
)
plot_A_20



plot_list <- list()
plot_item <- c("NP", "FA")
title <- c("", "")

modified_ticx = list(np_actual, fa_actual, FR_actual, RS_actual, H_actual , DS_actual)

configuration = 30
for (item in 1:length(plot_item)){
  plot = model_plot_sectionA(model_30, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")
dummy_PR <- SectionA_draw_dummy_plot("", "")
dummy_TS <- SectionA_draw_dummy_plot("", "")


plot_A_30 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_TS,
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 5
)
plot_A_30

 # + annotate(geom = 'text', x=.99, y=.5, label="S 30%", angle = 90, face = "bold")


plot_list <- list()
plot_item <- c("NP", "FA", "BF", "PR")
title <- c("", "", "", "")

modified_ticx = list(np_actual, fa_actual, BF_actual, PR_actual, H_actual, H_actual)
configuration = 50
for (item in 1:length(plot_item)){
  plot = model_plot_sectionA(model_50, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_TS <- SectionA_draw_dummy_plot("", "")


plot_A_50 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_TS,
  plot_list[[3]],
  plot_list[[4]],
  nrow = 1,
  ncol = 5
)
plot_A_50


library(cowplot)
Research_tactics<- plot_grid(plot_A_20, plot_A_30, plot_A_50, nrow = 3)
filename <- "SR_prediction_SectionA.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  Research_tactics,
  width = 8.5,
  height = 5.5,
  units = "in"
)
```




## SectionB plots
```{r, echo=FALSE}

plot_list <- list()
plot_item <- c("H")
title <- c("h-index")

modified_ticx = list(H_actual)
configuration = 20
for (item in 1:length(plot_item)){
  plot = model_plot_sectionB(model_20, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("Faculty Rank", "")
dummy_PR <- SectionA_draw_dummy_plot("Research Style", "")




plot_B_20 <- ggarrange(
  plot_list[[1]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 3
)
plot_B_20




plot_list <- list()
plot_item <- c("FR", "RS")
title <- c("Faculty Rank", "Research Style")

modified_ticx = list(FR_actual, RS_actual)
configuration = 30
for (item in 1:length(plot_item)){
  plot = model_plot_sectionB(model_30, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionB_draw_dummy_plot("Faculty Rank", "", 30)

plot_B_30 <- ggarrange(
  dummy_BF,
  plot_list[[1]],
  plot_list[[2]],
  nrow = 1,
  ncol = 3
)
plot_B_30



plot_list <- list()
plot_item <- c("H")
title <- c("h-index")

modified_ticx = list(H_actual)

configuration = 50
for (item in 1:length(plot_item)){
  plot = model_plot_sectionB(model_50, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")
dummy_PR <- SectionA_draw_dummy_plot("", "")




plot_B_50 <- ggarrange(
  plot_list[[1]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 3
)
plot_B_50



scholar_profile<- plot_grid(plot_B_20, plot_B_30, plot_B_50, nrow = 3)
filename <- "SR_prediction_SectionB.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  scholar_profile,
  width = 8.5,
  height = 5.5,
  units = "in"
)

```


## SectionC plots
```{r, echo=FALSE}
dummy_BF <- SectionC_draw_dummy_plot("Trait Anxiety", "", 20)
dummy_PR <- SectionA_draw_dummy_plot("Deadline Stress", "")
dummy_E <- SectionA_draw_dummy_plot("Extraversion", "")


plot_C_20 <- ggarrange(
  dummy_BF,
  dummy_PR,
  dummy_E,
  nrow = 1,
  ncol = 3
)
plot_C_20




plot_list <- list()
plot_item <- c("TA", "DS")
title <- c("Trait Anxiety", "Deadline Stress")

modified_ticx = list(FR_actual, DS_actual)

for (item in 1:length(plot_item)){
  plot = model_plot_sectionB(model_30, plot_item[item], modified_ticx[[item]], title[item], 30)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")

plot_C_30 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_BF,
  nrow = 1,
  ncol = 3
)
plot_C_30



plot_list <- list()
plot_item <- c("E")
title <- c("h-index")

modified_ticx = list(H_actual)

for (item in 1:length(plot_item)){
  plot = model_plot_sectionB(model_50, plot_item[item], modified_ticx[[item]], title[item], "")
  plot_list[[length(plot_list) + 1]] <- plot
}



dummy_BF <- SectionB_draw_dummy_plot("Faculty Rank", "", 50)
dummy_PR <- SectionA_draw_dummy_plot("", "")




plot_C_50 <- ggarrange(
  dummy_BF,
  dummy_PR,
  plot_list[[1]],
  nrow = 1,
  ncol = 3
)
plot_C_50



Personality<- plot_grid(plot_C_20, plot_C_30, plot_C_50, nrow = 3)
filename <- "SR_prediction_SectionC.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  Personality,
  width = 8.5,
  height = 5.5,
  units = "in"
)

```


```{r, echo=FALSE}


A_B_C <-
  plot_grid(Research_tactics, scholar_profile, Personality, nrow = 3, labels = c("A", "B", "C")) + annotation_custom(grid.polygon(
    c(0.0, 0.25, 1),
    c(0.34, 0.34, 0.34),
    id = c(1, 1, 1),
    gp = gpar(lwd = 1.5)
  )) + annotation_custom(grid.polygon(
    c(0.0, 0.25, 1),
    c(0.67, 0.67, 0.67),
    id = c(1, 1, 1),
    gp = gpar(lwd = 1.5)
  ))

filename <- "SR_prediction_allSection.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  A_B_C,
  width = 8.5,
  height = 10,
  units = "in"
)
```






## Plot using GGplot with colors


```{r}
  data_file_name <- 'KeyData.csv'
  curated_data_dir <- file.path(project_directory, 'curated-data')
  plot_dir <- file.path(project_directory, 'Plots')

  lm_DF <-
    read.csv(file.path(curated_data_dir, data_file_name),
             stringsAsFactors = FALSE)

Zcrit<-1.96   ### critical value for 95% confidence intervals
  
ilink <- family(model_20)$linkinv
#tmpd<-data.frame(NP="2",FA="NSF",T="1",RS="HandsOff",H=mean(H), TA=mean(TA))
NP<-c("1","2","3",rep("1",16))
FA<-c(rep("1",3),"1","2","3","4","5","6",rep("1",10))
TS<-c(rep("1",9),"1","2",rep("1",8))
RS<-c(rep("1",11),"1","2", rep("1",6))
H<-rep(mean(lm_DF$H),19)
TA<-rep(mean(lm_DF$TA),19)
tmpd<-data.frame(NP,FA,TS,RS,H,TA)
ndata <- cbind(tmpd, setNames(as_tibble(predict(model_20, tmpd, se.fit = TRUE)[1:2]),
                                   c('fit_link','se_link')))
ndata <- mutate(ndata,
                fit_resp  = ilink(fit_link),
                Lower_limit = ilink(fit_link - (Zcrit * se_link)),
                Upper_limit = ilink(fit_link + (Zcrit * se_link)))
ndata
```




```{r, echo=FALSE}

sectionA_plots <-
  function(model_name,
           item,
           modified_ticks,
           title,
           configuration) {
    plot_df <- broom::augment(model_name, type.predict = "response")
    
    
    tgc <-
      summarySE(plot_df,
                measurevar = ".fitted",
                groupvars = c(item, "SR"))
    tgc <- tgc[, c(item, ".fitted")]
    colnames(tgc) <- c("Item",  "Value")
    
    
    if (item == "NP" | item == "H" | item == "TA") {
      y_title = bquote(~ italic("P"[.(configuration)]))
      y_text = element_text(face = "bold")
    } else{
      y_title = element_blank()
      y_text = element_blank()
    }
    
    
    if (configuration != 20) {
      plot_title_ = element_blank()
      
    }
    if (configuration == 20) {
      plot_title_ = element_text(hjust = 0.5,
                                 face = "bold",
                                 size = 7)
    }
    
    
    
    if (item == "NP" |
        item == "H" |
        item == "TA") {
      
      plot <- ggplot(data = tgc) +
      geom_pointrange(
        mapping = aes(x = Item, y = Value, color = Item),
        stat = "summary",
        fun.min = min,
        fun.max = max,
        fun = median
      ) + theme_bw() +
      theme(
        axis.text.y = y_text,
        plot.title = plot_title_,
        panel.grid = element_blank(),
        axis.text.x = element_text(face = "bold", size = 6),
        # axis.text.y = element_text(face = "bold", size = 6),
        legend.position = "none"
      ) +
      labs(y = y_title, x = "", title = title) + scale_y_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "0%",
          "0.25" = "25%",
          "0.50" = "50%",
          "0.75" = "75%",
          "1" = "100%"
        )
      ) + theme(axis.ticks.y = element_blank(),
                axis.ticks.x = element_blank()) + scale_color_manual(
                  breaks = c("1", "2", "3", "4", "5", "6"),
                  values = c("gray", "black", "salmon", "blue", "red", "maroon")
                ) + scale_x_discrete(labels = modified_ticks)
      
    } else{
      
      plot <- ggplot(data = tgc) +
      geom_pointrange(
        mapping = aes(x = Item, y = Value, color = Item),
        stat = "summary",
        fun.min = min,
        fun.max = max,
        fun = mean
      ) + theme_bw() +
      theme(
        axis.text.y = y_text,
        plot.title = plot_title_,
        panel.grid = element_blank(),
        axis.text.x = element_text(face = "bold", size = 6),
        # axis.text.y = element_text(face = "bold", size = 6),
        legend.position = "none"
      ) +
      labs(y = y_title, x = "", title = title) + scale_y_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "0%",
          "0.25" = "25%",
          "0.50" = "50%",
          "0.75" = "75%",
          "1" = "100%"
        )
      ) + theme(axis.ticks.y = element_blank(),
                axis.ticks.x = element_blank()) + scale_color_manual(
                  breaks = c("1", "2", "3", "4", "5", "6"),
                  values = c("gray", "black", "salmon", "blue", "red", "maroon")
                ) + scale_x_discrete(labels = modified_ticks)
    }
    
  
    

    print(plot)

    
  }
```




```{r}
sectionBC_plots <-
  function(model_name,
           item,
           modified_ticks,
           Plot_title,
           configuration) {
    # print(model_name)
    if (item == "H" | item == "TA") {
      y_title = bquote(~ italic("P"[.(configuration)]))
      
      y_text = element_text(face = "bold")
    } else{
      y_title = element_blank()
      y_text = element_blank()
    }
    
    
    if (configuration != 20) {
      plot_title_ = element_blank()
      
    }
    if (configuration == 20) {
      plot_title_ = element_text(hjust = 0.5,
                                 face = "bold",
                                 size = 7)
    }
    
    if (item == "H" | item == "TA" | item == "E") {
      plt = plot_model(model_name, type = "pred", terms = item) +
        theme_bw()+
        theme(
          plot.title = plot_title_,
          panel.grid = element_blank(),
          axis.text.x = element_text(face = "bold", size = 6),
          axis.text.y = element_text(face = "bold", size = 6)
        ) +
        labs(y = y_title, x = "", title = Plot_title) + scale_y_continuous(
          limits = c(0.0, 1),
          breaks = c(0.0, 0.25, 0.50, 0.75, 1),
          labels = c(
            "0.00" = "0%",
            "0.25" = "25%",
            "0.50" = "50%",
            "0.75" = "75%",
            "1" = "100%"
          )
        ) + theme(
          axis.text.y = y_text,
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank()
        )
      return(plt)
    } else {
      
      plot_df <- broom::augment(model_name, type.predict = "response")
      tgc <-
        summarySE(plot_df,
                  measurevar = ".fitted",
                  groupvars = c(item, "SR"))
      tgc <- tgc[, c(item, ".fitted")]
      colnames(tgc) <- c("Item",  "Value")
      
      plt <- ggplot(data = tgc) +
      geom_pointrange(
        mapping = aes(x = Item, y = Value, color = Item),
        stat = "summary",
        fun.min = min,
        fun.max = max,
        fun = mean
      ) + theme_bw() +
      theme(
        axis.text.y = y_text,
        plot.title = plot_title_,
        panel.grid = element_blank(),
        axis.text.x = element_text(face = "bold", size = 6),
        # axis.text.y = element_text(face = "bold", size = 6),
        legend.position = "none"
      ) +
      labs(y = y_title, x = "", title = title) + scale_y_continuous(
        limits = c(0.0, 1),
        breaks = c(0.0, 0.25, 0.50, 0.75, 1),
        labels = c(
          "0.00" = "0%",
          "0.25" = "25%",
          "0.50" = "50%",
          "0.75" = "75%",
          "1" = "100%"
        )
      ) + theme(axis.ticks.y = element_blank(),
                axis.ticks.x = element_blank()) + scale_color_manual(
                  breaks = c("1", "2", "3", "4", "5", "6"),
                  values = c("gray", "black", "salmon", "blue", "red", "maroon")
                ) + scale_x_discrete(labels = modified_ticks)
      return(plt)
    }
    
  }
```


## Sectiono A
```{r, echo=FALSE}
plot_list <- list()
plot_item <- c("NP", "FA", "TS")
title <- c("Number of Proposals", "Funding Agency", "Time of Submission")

modified_ticx = list(np_actual, fa_actual, TS_actual, H_actual)

configuration = 20
for (item in 1:length(plot_item)){
  plot = sectionA_plots(model_20, plot_item[item], modified_ticx[[item]], title[item], 20)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("Break Frequency", "")
dummy_PR <- SectionA_draw_dummy_plot("Pilot Research", "")


plot_A_20 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  plot_list[[3]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 5
)
plot_A_20







plot_list <- list()
plot_item <- c("NP", "FA")
title <- c("", "")

modified_ticx = list(np_actual, fa_actual, FR_actual, RS_actual, H_actual , DS_actual)

configuration = 30
for (item in 1:length(plot_item)){
  plot = sectionA_plots(model_30, plot_item[item], modified_ticx[[item]], title[item], 30)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")
dummy_PR <- SectionA_draw_dummy_plot("", "")
dummy_TS <- SectionA_draw_dummy_plot("", "")


plot_A_30 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_TS,
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 5
)
plot_A_30

 # + annotate(geom = 'text', x=.99, y=.5, label="S 30%", angle = 90, face = "bold")


plot_list <- list()
plot_item <- c("NP", "FA", "BF", "PR")
title <- c("", "", "", "")

modified_ticx = list(np_actual, fa_actual, BF_actual, PR_actual, H_actual, H_actual)
for (item in 1:length(plot_item)){
  plot = sectionA_plots(model_50, plot_item[item], modified_ticx[[item]], title[item], 50)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_TS <- SectionA_draw_dummy_plot("", "")


plot_A_50 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_TS,
  plot_list[[3]],
  plot_list[[4]],
  nrow = 1,
  ncol = 5
)
plot_A_50


library(cowplot)
Research_tactics<- plot_grid(plot_A_20, plot_A_30, plot_A_50, nrow = 3)
filename <- "SR_prediction_SectionA_COLORED.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  Research_tactics,
  width = 8.5,
  height = 5.5,
  units = "in"
)

```


## Section B

```{r, echo=FALSE}
plot_list <- list()
plot_item <- c("H")
title <- c("h-index")

modified_ticx = list(H_actual)
configuration = 20
for (item in 1:length(plot_item)){
  plot = sectionBC_plots(model_20, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("Faculty Rank", "")
dummy_PR <- SectionA_draw_dummy_plot("Research Style", "")




plot_B_20 <- ggarrange(
  plot_list[[1]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 3
)
plot_B_20




plot_list <- list()
plot_item <- c("FR", "RS")
title <- c("Faculty Rank", "Research Style")

modified_ticx = list(FR_actual, RS_actual)
configuration = 30
for (item in 1:length(plot_item)){
  plot = sectionBC_plots(model_30, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionB_draw_dummy_plot("Faculty Rank", "", 30)

plot_B_30 <- ggarrange(
  dummy_BF,
  plot_list[[1]],
  plot_list[[2]],
  nrow = 1,
  ncol = 3
)
plot_B_30



plot_list <- list()
plot_item <- c("H")
title <- c("h-index")

modified_ticx = list(H_actual)

configuration = 50
for (item in 1:length(plot_item)){
  plot = sectionBC_plots(model_50, plot_item[item], modified_ticx[[item]], title[item], configuration)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")
dummy_PR <- SectionA_draw_dummy_plot("", "")




plot_B_50 <- ggarrange(
  plot_list[[1]],
  dummy_BF,
  dummy_PR,
  nrow = 1,
  ncol = 3
)
plot_B_50



scholar_profile<- plot_grid(plot_B_20, plot_B_30, plot_B_50, nrow = 3)
filename <- "SR_prediction_SectionB_colored.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  scholar_profile,
  width = 8.5,
  height = 5.5,
  units = "in"
)

```

## SectionC plots
```{r, echo=FALSE}
dummy_BF <- SectionC_draw_dummy_plot("Trait Anxiety", "", 20)
dummy_PR <- SectionA_draw_dummy_plot("Deadline Stress", "")
dummy_E <- SectionA_draw_dummy_plot("Extraversion", "")


plot_C_20 <- ggarrange(
  dummy_BF,
  dummy_PR,
  dummy_E,
  nrow = 1,
  ncol = 3
)
plot_C_20




plot_list <- list()
plot_item <- c("TA", "DS")
title <- c("Trait Anxiety", "Deadline Stress")

modified_ticx = list(FR_actual, DS_actual)

for (item in 1:length(plot_item)){
  plot = sectionBC_plots(model_30, plot_item[item], modified_ticx[[item]], title[item], 30)
  plot_list[[length(plot_list) + 1]] <- plot
}


dummy_BF <- SectionA_draw_dummy_plot("", "")

plot_C_30 <- ggarrange(
  plot_list[[1]],
  plot_list[[2]],
  dummy_BF,
  nrow = 1,
  ncol = 3
)
plot_C_30



plot_list <- list()
plot_item <- c("E")
title <- c("h-index")

modified_ticx = list(H_actual)

for (item in 1:length(plot_item)){
  plot = sectionBC_plots(model_50, plot_item[item], modified_ticx[[item]], title[item], "")
  plot_list[[length(plot_list) + 1]] <- plot
}



dummy_BF <- SectionB_draw_dummy_plot("Faculty Rank", "", 50)
dummy_PR <- SectionA_draw_dummy_plot("", "")




plot_C_50 <- ggarrange(
  dummy_BF,
  dummy_PR,
  plot_list[[1]],
  nrow = 1,
  ncol = 3
)
plot_C_50



Personality<- plot_grid(plot_C_20, plot_C_30, plot_C_50, nrow = 3)
filename <- "SR_prediction_SectionC_colored.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  Personality,
  width = 8.5,
  height = 5.5,
  units = "in"
)

```
```{r, echo=FALSE}
A_B_C <-
  plot_grid(Research_tactics, scholar_profile, Personality, nrow = 3, labels = c("A", "B", "C")) + annotation_custom(grid.polygon(
    c(0.0, 0.25, 1),
    c(0.34, 0.34, 0.34),
    id = c(1, 1, 1),
    gp = gpar(lwd = 1.5)
  )) + annotation_custom(grid.polygon(
    c(0.0, 0.25, 1),
    c(0.67, 0.67, 0.67),
    id = c(1, 1, 1),
    gp = gpar(lwd = 1.5)
  ))

filename <- "SR_prediction_allSection_colored.pdf"
full_path <- file.path(plot_dir, filename)
ggsave(
  full_path,
  A_B_C,
  width = 8.5,
  height = 10,
  units = "in"
)
```

