---
title: ''
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)
library(ggwordcloud)
library(dplyr)
# install.packages("wordcloud2")
```


```{r, echo=FALSE}
root_dir <- getwd()
project_directory<-dirname(root_dir)
data_dir <- file.path(project_directory, 'raw-data')
curated_data_dir <- file.path(project_directory, 'curated-data')
plot_dir <- file.path(project_directory, 'Plots')
data_file_name<-'world_cloud_stressful_new.csv'
data_file_name_std<-'world_cloud_helpful.csv'
data_file_name_suggestion<-'word_cloud_suggestions.csv'


Stressful<-read.csv(file.path(curated_data_dir,data_file_name),stringsAsFactors = FALSE)
Notstressful<-read.csv(file.path(curated_data_dir,data_file_name_std),stringsAsFactors = FALSE)
Suggestion<-read.csv(file.path(curated_data_dir,data_file_name_suggestion),stringsAsFactors = FALSE)

```


```{r, echo=FALSE}
word_cloud <- function(Data, Title) {
  wc <-
    ggplot(Data, aes(
      label = item,
      size = count,
      color = factor(sample.int(10, nrow(Data), replace = TRUE))
    )) +
    geom_text_wordcloud_area() +
    scale_size_area(max_size = 24) +
    theme_minimal() +
    ggtitle("Deadlines are stressful") +
    theme(plot.title = element_text(hjust = 0.5))
  
  return(wc)
}

```

## Stressful
```{r, echo=FALSE, warning=FALSE}
# Notstressful$item=tolower(Notstressful$item)
# set.seed(1234)
# wordcloud2(Notstressful,size=1 , shape = 'circle')


Stressful$item=tolower(Stressful$item)
set.seed(1234)
wc_stressful <- word_cloud(Stressful, "Deadlines are stressful")
wc_stressful
```



## NotStressful
```{r, echo=FALSE, warning=FALSE}
Notstressful$item=tolower(Notstressful$item)
set.seed(1234)


wc_helpfulful <- word_cloud(Notstressful, "Deadlines are helpfulful")
wc_helpfulful
```

##  Improvment suggestions
```{r, echo=FALSE, warning=FALSE}
Suggestion <- Suggestion %>% rename(item = "ï..item")
Suggestion$item=tolower(Suggestion$item)
set.seed(1234)


wc_helpfulful <- word_cloud(Suggestion, "Improvment suggestions")
wc_helpfulful
```





