---
title: "Timeline"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotrix)
library(plotly)
library(grid)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(reshape2)
library(plyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(stringr)
```


```{r, echo=FALSE}
root_dir <- getwd()
project_directory <- dirname(root_dir)
data_dir <- file.path(project_directory, 'curated-data')
plot_dir <- file.path(project_directory, 'Plots')
data_file_name <- 'StandardPart.csv'
curated_data_dir <- file.path(project_directory, 'curated-data')
StandardPart <-
  read.csv(file.path(data_dir, data_file_name), stringsAsFactors = FALSE)
```

```{r, echo=FALSE}
StandardPart <- StandardPart[StandardPart$funding_proposal=="Yes",]

StandardPart <- StandardPart[StandardPart$refereed_conference=="Yes",]
```



```{r, echo=FALSE}
title_list = c(
  "States",
  "Salary dependance on external grants",
  "Percentage of research operations funded by external grants",
  "Any looming deadline- Today/Next couple of days?",
  "Today's workload",
  "Workplace",
  "Research style",
  "Working hours- In a typical week",
  "Break frequency",
  "Email response style",
  "Participants submitting funding proposals",
  "Average number of proposals per year",
  "Funding agencies",
  "Perceived proposal success rate",
  "Length of proposal composition period",
  "Length of supporting research for proposals",
  "Proposal deadline week workload wrt a typical week",
  "Timing of proposal submission",
  "Stress level on proposal deadlines wrt regular working days",
  "Participants submitting papers in refereed conferences",
  "Average number of conference papers per year",
  "CORE rank of conferences",
  "Perceived success rate in  conference submissions",
  "Length of conference paper composition period",
  "Length of supporting research for conference papers",
  "Conference deadline week workload wrt a typical week",
  "Timing of conference paper submission",
  "Stress level on conference deadlines wrt regular working days"
)

```





```{r, echo=FALSE, warning=FALSE}
Core_Questions <-
  StandardPart %>% dplyr::select(
    record_id,
    state_do_you_reside,
    how_many_months_of_your_sa,
    what_is_your_current_level,
    do_you_have_a_deadline_tod,
    please_indicate_your_workl,
    where_you_typically_wor,
    test,
    in_a_typical_workday_how_m,
    in_a_typical_day_how_often,
    how_do_you_usually_handle,
    funding_proposal,
    what_is_the_average_number,
    funding_agency,
    hy,
    how_far_in_advance_do_you,
    what_is_the_length_of_supp,
    in_the_week_leading_to_a_p,
    when_you_typically_subm,
    stress_level_in_a_fundi,
    refereed_conference,
    wha_average_number,
    core_rank,
    if_you_submit_manuscripts,
    far_in_advance_do_you,
    length_of_supp,
    in_the_week_leading_to_a_c,
    you_typically_subm,
    ss_level_in_a_fundi
  )



Core_Questions<-Core_Questions  %>%  dplyr::rename(
                                          # h_index="google_scholar_h_index",
                                           Record_id="record_id",
                                           State="state_do_you_reside",
                                           S_D_E="how_many_months_of_your_sa",     ## salary depends on external grants
                                           RO_F_EG="what_is_your_current_level",   ## Research operations funded by external grants
                                           Deadline_today="do_you_have_a_deadline_tod",
                                           Workload_today="please_indicate_your_workl",
                                           Workplace="where_you_typically_wor",
                                           R_Style="test",                         ## Research Style
                                           TW_W_H="in_a_typical_workday_how_m",    ## Typical week working hours
                                           # TW_Research="ti_research",              ## Typical week Research
                                           Break="in_a_typical_day_how_often",     ## Break Frequency
                                           Email="how_do_you_usually_handle",      ## Email respnse style
                                           A_N_Pro="what_is_the_average_number",   ## Average Number of Proposal per year
                                           Success="hy",                           ## Success Rate in the proposal
                                           Com_Proposal="how_far_in_advance_do_you",# Composing Proposal
                                           L_Of_SR="what_is_the_length_of_supp",   ## Length of supporting research
                                           W_WB_PD="in_the_week_leading_to_a_p",   ## Work load a week before Proposal Deadline
                                           # Research_WB="week_research",            ## Research percentage a week before Proposal
                                           # Research_DD="proposal_research",        ## Research percentage in the Proposal deadlines day
                                           Submit_P="when_you_typically_subm",     ## Submit Proposal
                                           Stress_PD="stress_level_in_a_fundi",    ## Stress leven on Proposal Deadline
                                           A_N_Conf_Pap="wha_average_number"
                                           )


East = 'Connecticut|Maryland|Massachusetts|^New Jersey$|^New York$|Pennsylvania'
West = 'Arizona|California|Colorado|Nevada|^New Mexico$|Oregon'
Midwest = 'Illinois|Michigan|Minnesota|Ohio|Wisconsin'
South = 'Florida|Georgia|Tennessee|Texas|Virginia|Alabama'


  Core_Questions <- Core_Questions %>%
    mutate(States_ewns = case_when(str_detect(State, East)~'East',
                                   str_detect(State, West)~'West',
                                   str_detect(State, Midwest)~'Midwest',
                                   str_detect(State, South)~'South'))
  Core_Questions$State <- Core_Questions$States_ewns
  
  Core_Questions$States_ewns <- NULL
```



```{r, echo=FALSE}
count(Core_Questions$Break)
for(i in 1:nrow(Core_Questions)){
  
  #######---------Salary depends of external grants------------#################
  if (Core_Questions$S_D_E[i]=="Three months"){
    Core_Questions$S_D_E[i]="Three months"
  }else if (Core_Questions$S_D_E[i]=="2 months" || Core_Questions$S_D_E[i]==2){
    Core_Questions$S_D_E[i]="Two months"
  }else{
    Core_Questions$S_D_E[i]="Other"
  }


  if (Core_Questions$RO_F_EG[i]=="Not funded"){
    Core_Questions$RO_F_EG[i]="Not funded"
  } else if (Core_Questions$RO_F_EG[i]=="25-1%"){
    Core_Questions$RO_F_EG[i]="1-25%"
  } else if (Core_Questions$RO_F_EG[i]=="50-25%"){
    Core_Questions$RO_F_EG[i]="25-50%"
  } else if (Core_Questions$RO_F_EG[i]=="75-50%"){
    Core_Questions$RO_F_EG[i]="50-75%"
  } else if (Core_Questions$RO_F_EG[i]=="100-75%"){
    Core_Questions$RO_F_EG[i]="75-100%"
  } else{
    Core_Questions$RO_F_EG[i]="Fully funded"
  }
  
  
  if (Core_Questions$Workplace[i]=="Home"){
    Core_Questions$Workplace[i]="Home"
  } else if (Core_Questions$Workplace[i]=="Office"){
    Core_Questions$Workplace[i]="Office"
  } else {
    Core_Questions$Workplace[i]="Other"
  }

  if (Core_Questions$Email[i]=="Answer email in batches once  or twice per day"){
    Core_Questions$Email[i]="Reply Once/Twice"
  }else {
    Core_Questions$Email[i]="Reply instantly"
  }

  
  
  
  if (Core_Questions$Break[i]=="Every 1-2 hours"){
    Core_Questions$Break[i]="Every 1-2 hours"
  } else if (Core_Questions$Break[i]=="Every 3-4 hours"){
    Core_Questions$Break[i]="Every 3-4 hours"
  } else if (Core_Questions$Break[i]=="Every hour"){
    Core_Questions$Break[i]="Every hour"
  } else{
    Core_Questions$Break[i]="Other"
  }
  
  
  
  if (Core_Questions$funding_agency[i]=="NSF"){
    Core_Questions$funding_agency[i]="NSF"
  } else if (Core_Questions$funding_agency[i]=="NIH"){
    Core_Questions$funding_agency[i]="NIH"
  } else if (Core_Questions$funding_agency[i]=="DOE"){
    Core_Questions$funding_agency[i]="DOE"
  } else if (Core_Questions$funding_agency[i]=="DOD"){
    Core_Questions$funding_agency[i]="DOD"
  } else if (Core_Questions$funding_agency[i]=="NASA"){
    Core_Questions$funding_agency[i]="NASA"
  }  else{
    Core_Questions$funding_agency[i]="Other"
  }
  
  
  if (Core_Questions$Submit_P[i]=="Minutes before deadline"){
    Core_Questions$Submit_P[i]="Minutes before"
  } else if (Core_Questions$Submit_P[i]=="1-3 hours before deadline"){
    Core_Questions$Submit_P[i]="1-3 hours before"
  } else if (Core_Questions$Submit_P[i]=="3-6 hours before deadline"){
    Core_Questions$Submit_P[i]="3-6 hours before"
  }  else if (Core_Questions$Submit_P[i]=="1 day before deadline"){
    Core_Questions$Submit_P[i]="1 day before"
  } else if (Core_Questions$Submit_P[i]==""){
    Core_Questions$Submit_P[i]=NA
  } else {
    Core_Questions$Submit_P[i]="2 or more days before"
  }
  
    if (Core_Questions$you_typically_subm[i]=="Minutes before deadline"){
    Core_Questions$you_typically_subm[i]="Minutes before"
  } else if (Core_Questions$you_typically_subm[i]=="1-3 hours before deadline"){
    Core_Questions$you_typically_subm[i]="1-3 hours before"
  } else if (Core_Questions$you_typically_subm[i]=="3-6 hours before deadline"){
    Core_Questions$you_typically_subm[i]="3-6 hours before"
  }  else if (Core_Questions$you_typically_subm[i]=="1 day before deadline"){
    Core_Questions$you_typically_subm[i]="1 day before"
  } else if (Core_Questions$you_typically_subm[i]==""){
    Core_Questions$you_typically_subm[i]=NA
  } else {
    Core_Questions$you_typically_subm[i]="2 or more days before"
  }
  
  
  if (Core_Questions$Stress_PD[i] == "Extremely less"){
    Core_Questions$Stress_PD[i] = "Significantly less"
  } else if (Core_Questions$Stress_PD[i] == "Significantly less"){
    Core_Questions$Stress_PD[i] = "Less"
  } else if (Core_Questions$Stress_PD[i] == "Same"){
    Core_Questions$Stress_PD[i] = "About the same"
  } else if (Core_Questions$Stress_PD[i] == "Significantly  more"){
    Core_Questions$Stress_PD[i] = "More"
  } else if (Core_Questions$Stress_PD[i] == "Extremely  more"){
    Core_Questions$Stress_PD[i] = "Significantly more"
  } else {
    Core_Questions$Stress_PD[i] = NA
  }
  
  
    if (Core_Questions$ss_level_in_a_fundi[i] == "Extremely less"){
    Core_Questions$ss_level_in_a_fundi[i] = "Significantly less"
  } else if (Core_Questions$ss_level_in_a_fundi[i] == "Significantly less"){
    Core_Questions$ss_level_in_a_fundi[i] = "Less"
  } else if (Core_Questions$ss_level_in_a_fundi[i] == "Same"){
    Core_Questions$ss_level_in_a_fundi[i] = "About the same"
  } else if (Core_Questions$ss_level_in_a_fundi[i] == "Significantly  more"){
    Core_Questions$ss_level_in_a_fundi[i] = "More"
  } else if (Core_Questions$ss_level_in_a_fundi[i] == "Extremely  more"){
    Core_Questions$ss_level_in_a_fundi[i] = "Significantly more"
  } else {
    Core_Questions$ss_level_in_a_fundi[i] = NA
  }
  
  
}
  levels(factor(Core_Questions$Stress_PD))
  count(Core_Questions$State)
```

```{r}
  levels(factor(Core_Questions$State))
  levels(factor(Core_Questions$S_D_E))
  levels(factor(Core_Questions$RO_F_EG))
  levels(factor(Core_Questions$Deadline_today))
  levels(factor(Core_Questions$Workload_today))
  levels(factor(Core_Questions$Workplace))
  levels(factor(Core_Questions$R_Style))
  levels(factor(Core_Questions$TW_W_H))
  levels(factor(Core_Questions$Break))
  levels(factor(Core_Questions$Email))
  levels(factor(Core_Questions$funding_proposal))
  levels(factor(Core_Questions$A_N_Pro))
  levels(factor(Core_Questions$funding_agency))
  levels(factor(Core_Questions$Success))
  levels(factor(Core_Questions$Com_Proposal))
  levels(factor(Core_Questions$L_Of_SR))
  levels(factor(Core_Questions$W_WB_PD))
  levels(factor(Core_Questions$Submit_P))
  levels(factor(Core_Questions$Stress_PD))
  levels(factor(Core_Questions$refereed_conference))
  levels(factor(Core_Questions$A_N_Conf_Pap))
  levels(factor(Core_Questions$core_rank))
  levels(factor(Core_Questions$if_you_submit_manuscripts))
  levels(factor(Core_Questions$far_in_advance_do_you))
  levels(factor(Core_Questions$length_of_supp))
  levels(factor(Core_Questions$in_the_week_leading_to_a_c))
  levels(factor(Core_Questions$you_typically_subm))
  levels(factor(Core_Questions$ss_level_in_a_fundi))
  
  
  count(Core_Questions$funding_agency)
```


```{r, echo=FALSE}


list1 = c("East", "West", "Midwest", "South")
list2 = c("Two months", "Three months", "Other")

list3 = c("Not funded",
          "1-25%",
          "25-50%",
          "50-75%",
          "75-100%",
          "Fully funded")
list4 = c("No", "Yes")

list5 = c("Light", "Standard", "Heavy")
list6 = c("Home", "Office", "Other")

list7 = c("Hands-off", "Hands-on")
list8 = c("< 30", "30-40", "40-50", "> 50")

list9 = c("Every hour", "Every 1-2 hours", "Every 3-4 hours", "Other")
list10 = c("Reply instantly", "Reply Once/Twice")

list11 = c("No", "Yes")
list12 = c("1-2", "3-4", "5-6", "7-9", ">=10")

list13 = c("NSF", "NIH", "DOE","DOD", "NASA",  "Other")
list14 = c("< 10%", "10-20%", "20-30%", "30-50%", "50-75%", "75-90%", "> 90%")

list15 = c("1-2 weeks", "2-4 weeks", "1-2 months", "> 2 months")
list16 = c("< 1 month", "1-3 months", "3-6 months", "6-12 months", "> 12 months")

list17 = c("Significantly less", "Less", "About the same", "More", "Significantly more")
list18 = c(
  "Minutes before",
  "1-3 hours before",
  "3-6 hours before",
  "1 day before",
  "2 or more days before"
)

list19 = c("Significantly less", "Less", "About the same", "More", "Significantly more")

list20 = c("No", "Yes")

list21 = c("1-2", "3-4", "5-6", "7-9", ">= 10")
list22 = c("C", "B", "A", "A*")

list23 = c("< 10%", "10-20%", "20-30%", "30-50%", "50-75%", "75-90%", "> 90%")
list24 = c("< 1 week", "1-2 weeks", "2-4 weeks", "1-2 months", "> 2 months")

list25 = c("< 1 month", "1-3 months", "3-6 months", "6-12 months", "> 12 months")
list26 = c( "Significantly less","Less","About the same", "More", "Significantly more")

list27 = c(
  "Minutes before",
  "1-3 hours before",
  "3-6 hours before",
  "1 day before",
  "2 or more days before"
)

# "Extremely less",
# "Significantly less",

list28 = c("Significantly less", "Less", "About the same", "More", "Significantly more")

Ticks_list <-
  list(list1,
       list2,
       list3,
       list4,
       list5,
       list6,
       list7,
       list8,
       list9,
       list10,
       list11,
       list12,
       list13,
       list14,
       list15,
       list16,
       list17,
       list18,
       list19,
       list20,
       list21,
       list22,
       list23,
       list24,
       list25,
       list26,
       list27,
       list28)
```

```{r, echo=FALSE}



plot_list <- list()

time_line_plots <- c(13, 16, 17, 22, 25, 26)
for (i in time_line_plots) {

  if (i==13 |i==22){
    y_title = "Responses"
  } else{
    y_title = ""
  }
  
  ylimit = 100
  
  temp <- count(Core_Questions[i])
  colnames(temp) <- c("item", "count")
  temp <- temp[!(temp$item == ""), ]
  temp <- temp[order(temp$count),]
  temp <- temp[complete.cases(temp), ]
  
  bar_plot <- ggplot(data = temp, aes(x = item, y = count)) +
    geom_bar(stat = "identity",
             width = 0.5,
             fill = "steelblue") +
    theme_bw() +
    scale_y_continuous(breaks = seq(0, ylimit, by = 50),
                       limits = c(0, ylimit)) +
    labs(x = "", y = y_title, title = title_list[i - 1]) +
    theme(
      text = element_text(size = 6),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5, size = 7),
      axis.text.x = element_text(
        face = "bold",
        size = 6 ,
        angle = 30,
        hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 6)
    ) + scale_x_discrete(limits = Ticks_list[[i - 1]])

  print(bar_plot)
  
  plot_list[[length(plot_list) + 1]] <- bar_plot
}


final_plot <- ggarrange(plotlist = plot_list,
                      nrow = 2,
                      ncol = 3)



  filename <- "Summary.pdf"
  full_path <- file.path(plot_dir, filename)
  ggsave(
    full_path,
    final_plot,
    width = 8.5,
    height = 5.5,
    units = "in"
  )
```
```{r, echo=FALSE}
Timeline <- as.data.frame(cbind(NP = Core_Questions$A_N_Pro, PCP_weeks = Core_Questions$Com_Proposal, NC = Core_Questions$A_N_Conf_Pap, CCP_weeks = Core_Questions$far_in_advance_do_you)) 


levels(factor(Timeline$NP))
```

```{r, echo=FALSE}



Timeline <- Timeline %>%
  mutate(NP = recode(NP, "1-2" = 2, "3-4" = 4,"5-6" = 6, "7-9" = 7, ">=10" = 10)) %>% 
  mutate(NC = recode(NC, "1-2" = 1, "3-4" = 3,"5-6" = 5, "7-9" = 7, ">= 10" = 10)) %>% 
  mutate(PCP_weeks = recode(PCP_weeks, "< 1 week" = 1, "1-2 weeks" = 2,"2-4 weeks" = 4, "1-2 months" = 8, "> 2 months" = 12)) %>% 
  mutate(CCP_weeks = recode(CCP_weeks, "< 1 week" = 1, "1-2 weeks" = 2,"2-4 weeks" = 3, "1-2 months" = 6, "> 2 months" = 8))
  

Timeline_mean <- Timeline %>% summarise_all(mean)
Timeline_mean <- floor(Timeline_mean)

Timeline_melt <- melt(Timeline_mean)



  bar_plot <- ggplot(data = Timeline_melt, aes(x = variable, y = value)) +
    geom_bar(stat = "identity",
             width = 0.5,
             fill = "steelblue") +
    theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5, size = 12),
      axis.text.x = element_text(face = "bold", size = 10)
    ) + xlab("") + ylab("") + ggtitle("Average number of proposals, papers, and composition period [ in week ]")
    
  
  print(bar_plot) 
# Timeline_mean$Proposal_Weeks <- Timeline_mean$NP * Timeline_mean$PCP
# Timeline_mean$Conf_Weeks <- Timeline_mean$NC * Timeline_mean$CCP


```


```{r, echo=FALSE}
library(ggplot2)

df <- data.frame(y = seq(1, 53, by = 1), x = 1)

df.labs <-
  data.frame(y = Timeline_melt$value,
             lab = Timeline_melt$variable)

Timeline_plot <- ggplot(df, aes(x = x, y = y, fill = y)) +
  geom_tile() +
  geom_text(data = df.labs, aes(x = 1, y = 18, label = "Working period on Proposal"), size=4) +
  geom_text(data = df.labs, aes(x = 1, y = 42, label = "Working period on Conf. Paper"), size=4) +
  geom_hline(yintercept=c(32), size=1, linetype="dashed") +
  scale_fill_gradient(low = "green", high = "red", guide = FALSE) +
  coord_flip() +
  ggtitle("Timeline of an year") +
  theme_minimal() +
  theme(axis.text.x = element_text(face = "bold", size = 10),
        axis.title.x = element_text(face = "bold"))+
  scale_y_continuous(limits = c(1, 53), breaks = seq(2, 52, by = 10))+
  scale_x_continuous(breaks = pretty(df$y)) +
  xlab("") + 
  ylab("Weeks in a year") +  
  theme(aspect.ratio = 0.09, plot.title = element_text(hjust = 0.5))
Timeline_plot




final_plot <- ggarrange(bar_plot,Timeline_plot,
                      nrow = 2,
                      ncol = 1)



  filename <- "Timeline.pdf"
  full_path <- file.path(plot_dir, filename)
  ggsave(
    full_path,
    final_plot,
    width = 8.5,
    height = 5.5,
    units = "in"
  )
```

