---
title: "Supplement"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotrix)
library(plotly)
library(grid)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(reshape2)
library(plyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(janitor)
```


```{r, echo=FALSE}

root_dir <- getwd()
project_directory <- dirname(root_dir)
data_dir <- file.path(project_directory, 'curated-data')
plot_dir <- file.path(project_directory, 'Plots')
data_file_name <- 'Supplement_nlp.csv'
curated_data_dir <- file.path(project_directory, 'curated-data')
Data <-
  read.csv(file.path(data_dir, data_file_name), stringsAsFactors = FALSE)
```

```{r, echo=FALSE}
# Data<- StandardPart %>% select(faculty_rank, gender, please_write_about_any_oth, hy)

# colnames(Data) <- c("Rank", "Gender", "Comments", "SuccessRate")

# No_comments<- Data %>% remove_empty("rows")

No_comments <- Data[Data$Comments == "", ]
comments <- Data[Data$Comments != "", ]


table(Data$SR)
```

```{r, echo=FALSE, warning=FALSE}

ggplot(Data, aes(x = Rank)) + 
  geom_histogram(binwidth = .5, stat = "count") + theme_minimal() +
  ggtitle("Overall Rank of Participants") + theme(plot.title = element_text(hjust = 0.5)) +
        scale_y_continuous(breaks = seq(0, 200, by = 50),
                       limits = c(0, 200)) +
      theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(
        face = "bold",
        size = 10 ,
        # angle = 45,
        # hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 10)
    ) + xlab("")

```
\newpage
```{r, echo=FALSE, warning=FALSE}
table(No_comments$SR)

ggplot(No_comments, aes(x = SR)) + 
  geom_histogram(binwidth = .5, stat = "count") + theme_minimal() +
  ggtitle("Participant's Success Rate: Without comment") + theme(plot.title = element_text(hjust = 0.5)) +
  theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(
        face = "bold",
        size = 10 ,
        # angle = 45,
        # hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 10)
    ) + xlab("")

ggplot(No_comments, aes(x = Rank)) + 
  geom_histogram(binwidth = .5, stat = "count") + theme_minimal() +
  ggtitle("Participant's Rank: Without comment") + theme(plot.title = element_text(hjust = 0.5)) +
        scale_y_continuous(breaks = seq(0, 120, by = 30),
                       limits = c(0, 120)) +
  theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(
        face = "bold",
        size = 10 ,
        # angle = 45,
        # hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 10)
    ) + xlab("")
```

\newpage
```{r, echo=FALSE, warning=FALSE}

table(comments$SR)
ggplot(comments, aes(x = SR)) + 
  geom_histogram(binwidth = .5, stat = "count") + theme_minimal() +
  ggtitle("Participant's Success Rate: With comment") + theme(plot.title = element_text(hjust = 0.5)) +
      scale_y_continuous(breaks = seq(0, 120, by = 30),
                       limits = c(0, 120)) + theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(
        face = "bold",
        size = 10 ,
        # angle = 45,
        # hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 10)
    ) + xlab("")

ggplot(comments, aes(x = Rank)) + 
  geom_histogram(binwidth = .5, stat = "count") + theme_minimal() +
  ggtitle("Participant's Rank: With comment") + theme(plot.title = element_text(hjust = 0.5)) +
        scale_y_continuous(breaks = seq(0, 100, by = 25),
                       limits = c(0, 100)) +
  theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(
        face = "bold",
        size = 10 ,
        # angle = 45,
        # hjust = 1
      ),
      axis.text.y = element_text(face = "bold", size = 10)
    ) + xlab("")
```


